version: '2'
services:

  db:
    image: mdillon/postgis
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'buildout'
      POSTGRES_USER: 'buildout'
      POSTGRES_DB: 'lizard_damage'

  rabbit:
    image: rabbitmq

  web:
    build: .
    command: "bin/django runserver 0.0.0.0:5000"
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbit

  worker:
    build: .
    command: "bin/django celery worker --loglevel DEBUG"
    environment:
      C_FORCE_ROOT: 1
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbit

volumes:
  pgdata:
